In [2]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

<h2 id="about_dataset">About the dataset</h2>
We will use a telecommunications dataset for predicting customer churn. This is a historical customer dataset where each row represents one customer. The data is relatively easy to understand, and you may uncover insights you can use immediately. Typically it is less expensive to keep customers than acquire new ones, so the focus of this analysis is to predict the customers who will stay with the company. 

This data set provides information to help you predict what behavior will help you to retain customers. You can analyze all relevant customer data and develop focused customer retention programs.

The dataset includes information about:

-   Customers who left within the last month – the column is called Churn
-   Services that each customer has signed up for – phone, multiple lines, internet, online security, online backup, device protection, tech support, and streaming TV and movies
-   Customer account information – how long they had been a customer, contract, payment method, paperless billing, monthly charges, and total charges
-   Demographic info about customers – gender, age range, and if they have partners and dependents


In [8]:
churn_df = pd.read_csv('ChurnData.csv')
churn_df.head()

tenure   age  address  income   ed  ...  loglong  logtoll  lninc  custcat  churn
0    11.0  33.0      7.0   136.0  5.0  ...    1.482    3.033  4.913      4.0    1.0
1    33.0  33.0     12.0    33.0  2.0  ...    2.246    3.240  3.497      1.0    1.0
2    23.0  30.0      9.0    30.0  1.0  ...    1.841    3.240  3.401      3.0    0.0
3    38.0  35.0      5.0    76.0  2.0  ...    1.800    3.807  4.331      4.0    0.0
4     7.0  35.0     14.0    80.0  2.0  ...    1.960    3.091  4.382      3.0    0.0

[5 rows x 28 columns]

In [10]:
churn_df['churn'].value_counts()

0.0    142
1.0     58
Name: churn, dtype: int64

In [12]:
#Lets select some features for the modeling
churn_df = churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',   'callcard', 'wireless','churn']]
churn_df['churn'] = churn_df['churn'].astype('int')
churn_df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  churn
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0      1
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0      1
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0      0
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0      0
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0      0

In [13]:
churn_df.shape

(200, 10)

In [16]:
#Independent features of dataset
X = np.asarray(churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']])
X[0:5]

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.]])

In [17]:
y = np.asarray(churn_df['churn'])
y [0:5]

array([1, 1, 0, 0, 0])

In [18]:
from sklearn import preprocessing
X=preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695]])

In [19]:
from sklearn.model_selection import train_test_split


In [23]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=4)

In [24]:
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (140, 7) (140,)
Test set: (60, 7) (60,)


# Modeling Using LogisticRegression

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [27]:
yhat = LR.predict(X_test)
yhat

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1])

In [28]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.52298609, 0.47701391],
       [0.59233956, 0.40766044],
       [0.55590505, 0.44409495],
       [0.6152532 , 0.3847468 ],
       [0.55972887, 0.44027113],
       [0.55602976, 0.44397024],
       [0.51738442, 0.48261558],
       [0.59279307, 0.40720693],
       [0.40875887, 0.59124113],
       [0.61827685, 0.38172315],
       [0.5595258 , 0.4404742 ],
       [0.6039787 , 0.3960213 ],
       [0.47881301, 0.52118699],
       [0.42246615, 0.57753385],
       [0.65085116, 0.34914884],
       [0.54137361, 0.45862639],
       [0.50646954, 0.49353046],
       [0.46626657, 0.53373343],
       [0.47696672, 0.52303328],
       [0.51885069, 0.48114931],
       [0.60500651, 0.39499349],
       [0.51787841, 0.48212159],
       [0.61918205, 0.38081795],
       [0.51392756, 0.48607244],
       [0.49111532, 0.50888468],
       [0.68921321, 0.31078679],
       [0.53850055, 0.46149945],
       [0.50852374, 0.49147626],
       [0.51355385, 0.48644615],
       [0.69276371, 0.30723629],
       [0.

In [31]:
#Cheking accuracy of model using Logloss
from sklearn.metrics import log_loss
log_loss(y_test, yhat_prob)

0.5944887899737815